version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Map client port to localhost
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 server.wsgi:application
    volumes:
      - ./server:/app  # Mount the server directory for live changes
    ports:
      - "8000:8000"  # Map server port to localhost
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
