# Generated by Django 4.2.6 on 2024-09-21 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_rename_shops_shops_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shirts_updated', models.IntegerField(default=0)),
                ('pants_updated', models.IntegerField(default=0)),
                ('safari_updated', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='shops.shops')),
            ],
            options={
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
