# Generated by Django 4.2.6 on 2024-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='each_day_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
