# Generated by Django 4.2.6 on 2024-09-25 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shops_amount_to_bill_alter_shops_pants_price_and_more'),
        ('days', '0004_alter_day_each_day_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shirts_updated', models.IntegerField(default=0)),
                ('pants_updated', models.IntegerField(default=0)),
                ('safari_updated', models.IntegerField(default=0)),
                ('each_day_total', models.FloatField(default=0.0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_histories', to='shops.shops')),
            ],
            options={
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
