# Generated by Django 4.2.6 on 2024-09-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='custom_price',
        ),
    ]
