# Generated by Django 4.2.6 on 2024-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shops_custom_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='user',
            new_name='shops',
        ),
    ]
