# Generated by Django 4.2.6 on 2024-09-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_rename_user_shops_shops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='shops',
            new_name='user',
        ),
    ]
